Arac_Kiralama_Otomasyonu/Models/Rezervasyonlar.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervasyonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezervasyonlar()
        {
            this.EkSuruculer = new HashSet<EkSuruculer>();
            this.KiralamaUcretleri = new HashSet<KiralamaUcretleri>();
            this.Odemeler = new HashSet<Odemeler>();
        }
       
        public int rezervasyon_no { get; set; }
        public int arac_id { get; set; }
        public int musteri_id { get; set; }
        public System.DateTime baslangic_tarihi { get; set; }
        public System.DateTime bitis_tarihi { get; set; }
    
        public virtual Araclar Araclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EkSuruculer> EkSuruculer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiralamaUcretleri> KiralamaUcretleri { get; set; }
        public virtual Musteriler Musteriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Odemeler> Odemeler { get; set; }
    }
}

Arac_Kiralama_Otomasyonu/Controllers/RezervasyonlarsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Arac_Kiralama_Otomasyonu.Models;

namespace Arac_Kiralama_Otomasyonu.Controllers
{
    public class RezervasyonlarsController : Controller
    {
        private Arac_Kiralama_ProjesiEntities db = new Arac_Kiralama_ProjesiEntities();

        // GET: Rezervasyonlars
        public ActionResult Index()
        {

            if (Session["musterim"]!=null)
            {
                // Kullanıcı giriş yapmışsa, sadece bu kullanıcıya ait rezervasyonları getir
                int musteriID = ((Musteriler)Session["musterim"]).musteri_no;
                var rezervasyonlar = db.Rezervasyonlar.Include(r => r.Araclar).Include(r => r.Musteriler)
                                                     .Where(r => r.musteri_id == musteriID);
                return View(rezervasyonlar.ToList());
            }
            else
            {
                var rezervasyonlar = db.Rezervasyonlar.Include(r => r.Araclar).Include(r => r.Musteriler);
                return View(rezervasyonlar.ToList());
            }
           
        }

        // GET: Rezervasyonlars/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervasyonlar rezervasyonlar = db.Rezervasyonlar.Find(id);
            if (rezervasyonlar == null)
            {
                return HttpNotFound();
            }
            return View(rezervasyonlar);
        }

        // GET: Rezervasyonlars/Create
        public ActionResult Create()
        {
            if (Session["musterim"] == null)
            {
                // Kullanıcı giriş yapmamışsa uyarı mesajı oluştur
                ViewBag.ErrorMessage = "Lütfen giriş yapınız.";
            }
            else
            {
                ViewBag.ErrorMessage = null; // Giriş yapılmışsa uyarı mesajını temizle
            }
            ViewBag.arac_id = new SelectList(db.Araclar, "arac_no", "marka");
            ViewBag.musteri_id = new SelectList(db.Musteriler, "musteri_no", "ad");
            return View();
        }

        // POST: Rezervasyonlars/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "rezervasyon_no,arac_id,musteri_id,baslangic_tarihi,bitis_tarihi")] Rezervasyonlar rezervasyonlar)
        {
            if (ModelState.IsValid)
            {
                db.Rezervasyonlar.Add(rezervasyonlar);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.arac_id = new SelectList(db.Araclar, "arac_no", "marka", rezervasyonlar.arac_id);
            ViewBag.musteri_id = new SelectList(db.Musteriler, "musteri_no", "ad", rezervasyonlar.musteri_id);
            return View(rezervasyonlar);
        }

        // GET: Rezervasyonlars/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervasyonlar rezervasyonlar = db.Rezervasyonlar.Find(id);
            if (rezervasyonlar == null)
            {
                return HttpNotFound();
            }
            ViewBag.arac_id = new SelectList(db.Araclar, "arac_no", "marka", rezervasyonlar.arac_id);
            ViewBag.musteri_id = new SelectList(db.Musteriler, "musteri_no", "ad", rezervasyonlar.musteri_id);
            return View(rezervasyonlar);
        }

        // POST: Rezervasyonlars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "rezervasyon_no,arac_id,musteri_id,baslangic_tarihi,bitis_tarihi")] Rezervasyonlar rezervasyonlar)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rezervasyonlar).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.arac_id = new SelectList(db.Araclar, "arac_no", "marka", rezervasyonlar.arac_id);
            ViewBag.musteri_id = new SelectList(db.Musteriler, "musteri_no", "ad", rezervasyonlar.musteri_id);
            return View(rezervasyonlar);
        }

        // GET: Rezervasyonlars/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Rezervasyonlar rezervasyonlar = db.Rezervasyonlar.Find(id);
            if (rezervasyonlar == null)
            {
                return HttpNotFound();
            }
            return View(rezervasyonlar);
        }

        // POST: Rezervasyonlars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Rezervasyonlar rezervasyonlar = db.Rezervasyonlar.Find(id);
            db.Rezervasyonlar.Remove(rezervasyonlar);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Arac_Kiralama_Otomasyonu/Views/Rezervasyonlars/Create.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Rezervasyonlar

@{
    Layout = null;
}
@Styles.Render("~/Content/css")

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div>
        <!-- Hata mesajını buraya ekleyin -->
        @if (ViewBag.ErrorMessage != null)
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.ErrorMessage
            </div>
        }
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Rezervasyonlar</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.arac_id, "Araç", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("arac_id", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.arac_id, "", new { @class = "text-danger" })
        </div>
    </div>
   
   

    <div class="form-group">
        @Html.Label("musteri_id", "Müşteri Adı", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownList("musteri_id", null, htmlAttributes: new { @class = "form-control" })

            @Html.ValidationMessageFor(model => model.musteri_id, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.Label("Başlangıç Tarihi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.baslangic_tarihi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.baslangic_tarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Bitiş Tarihi", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.bitis_tarihi, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.bitis_tarihi, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-success" />
        </div>
    </div>
</div>
        <style>
            body {
                background-image: url('/template/images/hero-img.jpg'); /* Arka plan görseli */
                background-size: cover;
                background-position: center;
                font-family: Arial, sans-serif;
            }

            .login-form {
                max-width: 300px;
                margin: 0 auto;
                padding: 20px;
                border: 1px solid #ccc;
                border-radius: 5px;
                background-color: rgba(255, 255, 255, 0.8); /* Arka plan rengi (saydamlık ayarlı) */
            }

            .input-container {
                position: relative;
                margin-bottom: 15px;
            }

                .input-container input {
                    width: 100%;
                    padding: 10px;
                    border: 1px solid #ccc;
                    border-radius: 3px;
                }

                .input-container .icon {
                    position: absolute;
                    top: 12px;
                    left: 10px;
                    color: #888;
                }

                .input-container .fa-eye {
                    cursor: pointer;
                }

            .bttn {
                width: 100%;
                padding: 10px;
                border: none;
                border-radius: 3px;
                background-color: #007bff;
                color: #fff;
                font-size: 16px;
                cursor: pointer;
            }

                .bttn:hover {
                    background-color: #0056b3;
                }
        </style>
    }

    <div>
        @Html.ActionLink("Anasayfaya Dön", "Index","Home")
    </div>

</body>
</html>

Arac_Kiralama_Otomasyonu/Views/Rezervasyonlars/Delete.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Rezervasyonlar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Rezervasyonlar</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.baslangic_tarihi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.baslangic_tarihi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.bitis_tarihi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.bitis_tarihi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Araclar.marka)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Araclar.marka)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Musteriler.ad)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Musteriler.ad)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Arac_Kiralama_Otomasyonu/Views/Rezervasyonlars/Details.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Rezervasyonlar

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Rezervasyonlar</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.baslangic_tarihi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.baslangic_tarihi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.bitis_tarihi)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.bitis_tarihi)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Araclar.marka)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Araclar.marka)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Musteriler.ad)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Musteriler.ad)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.rezervasyon_no }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Arac_Kiralama_Otomasyonu/Views/Rezervasyonlars/Edit.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Rezervasyonlar

@{
    Layout = null;
}
@Styles.Render("~/Content/css")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Rezervasyonlar</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.rezervasyon_no)

            <div class="form-group">
                @Html.LabelFor(model => model.arac_id, "Araç", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("arac_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.arac_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.musteri_id, "Adınız", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("musteri_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.musteri_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.baslangic_tarihi,"Başlangıç Tarihi", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.baslangic_tarihi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.baslangic_tarihi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.bitis_tarihi,"Bitiş Tarihi", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.bitis_tarihi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.bitis_tarihi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                   
                    @Html.ActionLink("Kaydet", "Create")
                </div>

           
            </div>
        </div>
        <style>
            body {
                background-image: url('/template/images/hero-img.jpg'); /* Arka plan görseli */
                background-size: cover;
                background-position: center;
                font-family: Arial, sans-serif;
            }

            .login-form {
                max-width: 300px;
                margin: 0 auto;
                padding: 20px;
                border: 1px solid #ccc;
                border-radius: 5px;
                background-color: rgba(255, 255, 255, 0.8); /* Arka plan rengi (saydamlık ayarlı) */
            }

            .input-container {
                position: relative;
                margin-bottom: 15px;
            }

                .input-container input {
                    width: 100%;
                    padding: 10px;
                    border: 1px solid #ccc;
                    border-radius: 3px;
                }

                .input-container .icon {
                    position: absolute;
                    top: 12px;
                    left: 10px;
                    color: #888;
                }

                .input-container .fa-eye {
                    cursor: pointer;
                }

            .bttn {
                width: 100%;
                padding: 10px;
                border: none;
                border-radius: 3px;
                background-color: #007bff;
                color: #fff;
                font-size: 16px;
                cursor: pointer;
            }

                .bttn:hover {
                    background-color: #0056b3;
                }
        </style>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Arac_Kiralama_Otomasyonu/Views/Rezervasyonlars/Index.cshtml
@model IEnumerable<Arac_Kiralama_Otomasyonu.Models.Rezervasyonlar>

@{
    Layout = null;
}
@Styles.Render("~/Content/css")
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
   
    <p>
        @Html.ActionLink("Yeni Rezervasyon", "Create")
    </p>
    <table class="table">

        <tr>
            <th>
                Başlangıç Tarihi
            </th>
            <th>
                Bitiş Tarihi
            </th>
            <th>
                Marka
            </th>
            <th>
                Ad
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <input type="text" id="baslangicTarihi_@item.rezervasyon_no" name="baslangicTarihi" class="datepicker" value="@item.baslangic_tarihi.ToString("yyyy-MM-dd")" />
                </td>
                <td>
                    <input type="text" id="bitisTarihi_@item.rezervasyon_no" name="bitisTarihi" class="datepicker" value="@item.bitis_tarihi.ToString("yyyy-MM-dd")" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Araclar.marka)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Musteriler.ad)
                </td>
                <td>
                    <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("Edit", "Rezervasyonlars", new { id = item.rezervasyon_no })'">Edit</button>
                    <button type="button" class="btn btn-success" onclick="window.location.href='@Url.Action("Details", "Rezervasyonlars", new { id = item.rezervasyon_no })'">Details</button>
                    <button type="button" class="btn btn-success" onclick="if(confirm('Silmek istediğinize emin misiniz?')) window.location.href='@Url.Action("Delete", "Rezervasyonlars", new { id = item.rezervasyon_no })'">Delete</button>
                </td>

            </tr>
        }

    </table>
    <script>
        $("#dogtar").datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true,
            language: 'tr'
        });
    </script>
    <style>
        body {
            background-image: url('/template/images/hero-img.jpg'); /* Arka plan görseli */
            background-size: cover;
            background-position: center;
            font-family: Arial, sans-serif;
        }

        .login-form {
            max-width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: rgba(255, 255, 255, 0.8); /* Arka plan rengi (saydamlık ayarlı) */
        }

        .input-container {
            position: relative;
            margin-bottom: 15px;
        }

            .input-container input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ccc;
                border-radius: 3px;
            }

            .input-container .icon {
                position: absolute;
                top: 12px;
                left: 10px;
                color: #888;
            }

            .input-container .fa-eye {
                cursor: pointer;
            }

        .bttn {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 3px;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

            .bttn:hover {
                background-color: #0056b3;
            }
    </style>
    <div>
        @Html.ActionLink("Anasayfaya Dön", "Index", "Home")
    </div>
</body>
</html>