Arac_Kiralama_Otomasyonu/Models/Musteriler.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arac_Kiralama_Otomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Musteriler()
        {
            this.Degerlendirme = new HashSet<Degerlendirme>();
            this.Rezervasyonlar = new HashSet<Rezervasyonlar>();
        }
    
        public int musteri_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string email { get; set; }
        public string sifre { get; set; }
        public string telefon { get; set; }
        public int rol_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Degerlendirme> Degerlendirme { get; set; }
        public virtual KullaniciRolleri KullaniciRolleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyonlar> Rezervasyonlar { get; set; }
    }
}

Arac_Kiralama_Otomasyonu/Controllers/MusterilersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Arac_Kiralama_Otomasyonu.Models;

namespace Arac_Kiralama_Otomasyonu.Controllers
{
    public class MusterilersController : Controller
    {
        private Arac_Kiralama_ProjesiEntities db = new Arac_Kiralama_ProjesiEntities();

        // GET: Musterilers
        public ActionResult Index()
        {
            var musteriler = db.Musteriler.Include(m => m.KullaniciRolleri);
            return View(musteriler.ToList());
        }

        // GET: Musterilers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musteriler musteriler = db.Musteriler.Find(id);
            if (musteriler == null)
            {
                return HttpNotFound();
            }
            return View(musteriler);
        }

        // GET: Musterilers/Create
        public ActionResult Create()
        {
            ViewBag.rol_id = new SelectList(db.KullaniciRolleri, "rol_no", "rol_ad");
            return View();
        }

        // POST: Musterilers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "musteri_no,ad,soyad,email,sifre,telefon,rol_id")] Musteriler musteriler)
        {
            if (ModelState.IsValid)
            {
                musteriler.rol_id = 3;
                db.Musteriler.Add(musteriler);
                db.SaveChanges();
                return RedirectToAction("Index","Home");
            }

            ViewBag.rol_id = new SelectList(db.KullaniciRolleri, "rol_no", "rol_ad", musteriler.rol_id);
            return View(musteriler);
        }

        // GET: Musterilers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musteriler musteriler = db.Musteriler.Find(id);
            if (musteriler == null)
            {
                return HttpNotFound();
            }
            ViewBag.rol_id = new SelectList(db.KullaniciRolleri, "rol_no", "rol_ad", musteriler.rol_id);
            return View(musteriler);
        }

        // POST: Musterilers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "musteri_no,ad,soyad,email,sifre,telefon,rol_id")] Musteriler musteriler)
        {
            if (ModelState.IsValid)
            {
                musteriler.rol_id = 3;
                db.Entry(musteriler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.rol_id = new SelectList(db.KullaniciRolleri, "rol_no", "rol_ad", musteriler.rol_id);
            return View(musteriler);
        }

        // GET: Musterilers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Musteriler musteriler = db.Musteriler.Find(id);
            if (musteriler == null)
            {
                return HttpNotFound();
            }
            return View(musteriler);
        }

        // POST: Musterilers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Musteriler musteriler = db.Musteriler.Find(id);
            db.Musteriler.Remove(musteriler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Arac_Kiralama_Otomasyonu/Views/Musterilers/Create.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Musteriler

@{

    Layout = null;

}

<h2>ÜYE OL</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Ad", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Soyad", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.soyad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("E-mail", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <i class="fa fa-key icon"></i>
        @Html.Label("Şifre", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            <i class="fa fa-eye icon" onclick="togglePassword()"></i>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Kaydet" class="btn btn-success" />
        </div>
    </div>
</div>
    <style>
        body {
            background-image: url('/template/images/hero-img.jpg'); /* Arka plan görseli */
            background-size: cover;
            background-position: center;
            font-family: Arial, sans-serif;
        }

        .login-form {
            max-width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: rgba(255, 255, 255, 0.8); /* Arka plan rengi (saydamlık ayarlı) */
        }

        .input-container {
            position: relative;
            margin-bottom: 15px;
        }

            .input-container input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ccc;
                border-radius: 3px;
            }

            .input-container .icon {
                position: absolute;
                top: 12px;
                left: 10px;
                color: #888;
            }

            .input-container .fa-eye {
                cursor: pointer;
            }

        .bttn {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 3px;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

            .bttn:hover {
                background-color: #0056b3;
            }
    </style>

}

<div>
    @Html.ActionLink("Anasayfa", "Index", "Home")
</div>

Arac_Kiralama_Otomasyonu/Views/Musterilers/Delete.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Musteriler

@{
    Layout = null;
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Musteriler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KullaniciRolleri.rol_ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullaniciRolleri.rol_ad)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Arac_Kiralama_Otomasyonu/Views/Musterilers/Details.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Musteriler

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Musteriler</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.soyad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.soyad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sifre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sifre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.telefon)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.telefon)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.KullaniciRolleri.rol_ad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KullaniciRolleri.rol_ad)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.musteri_no }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Arac_Kiralama_Otomasyonu/Views/Musterilers/Edit.cshtml
@model Arac_Kiralama_Otomasyonu.Models.Musteriler

@{

    Layout = null;
}

<h2>Hesabım</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">


        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.musteri_no)

        <div class="form-group">
            @Html.Label("Ad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Soyad", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("E-mail", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <i class="fa fa-key icon"></i>
            @Html.Label("Şifre", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
                <i class="fa fa-eye icon" onclick="togglePassword()"></i>
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Telefon", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.telefon, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div class="btn-group mr-2" role="group">
                <input type="submit" value="Kaydet" class="btn btn-success" />
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div class="btn-group" role="group">
                <button type="button" class="btn btn-danger" id="btnDelete">Sil</button>
            </div>
        </div>
    </div>


    <script>
    document.getElementById("btnDelete").addEventListener("click", function () {
        if (confirm("Hesabınızı Silmek istediğinize emin misiniz?")) {
            window.location.href = '@Url.Action("Delete", "Musterilers", new { id = Model.musteri_no })';
        }
    });
    </script>


    <style>
        body {
            background-image: url('/template/images/hero-img.jpg'); /* Arka plan görseli */
            background-size: cover;
            background-position: center;
            font-family: Arial, sans-serif;
        }

        .login-form {
            max-width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: rgba(255, 255, 255, 0.8); /* Arka plan rengi (saydamlık ayarlı) */
        }

        .input-container {
            position: relative;
            margin-bottom: 15px;
        }

            .input-container input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ccc;
                border-radius: 3px;
            }

            .input-container .icon {
                position: absolute;
                top: 12px;
                left: 10px;
                color: #888;
            }

            .input-container .fa-eye {
                cursor: pointer;
            }

        .bttn {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 3px;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

            .bttn:hover {
                background-color: #0056b3;
            }
    </style>
}

<div>
    @Html.ActionLink("Anasayfaya Dön", "Index", "Home")
</div>

Arac_Kiralama_Otomasyonu/Views/Musterilers/Index.cshtml
@model IEnumerable<Arac_Kiralama_Otomasyonu.Models.Musteriler>

@{

    Layout = null;
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.soyad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sifre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.telefon)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.KullaniciRolleri.rol_ad)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.soyad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.sifre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.telefon)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KullaniciRolleri.rol_ad)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.musteri_no }) |
            @Html.ActionLink("Details", "Details", new { id=item.musteri_no }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.musteri_no })
        </td>
    </tr>
}

</table>