Arac_Kiralama_Otomasyonu/Controllers/AraclarsController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Arac_Kiralama_Otomasyonu.Models;
using PagedList;

namespace Arac_Kiralama_Otomasyonu.Controllers
{
    public class AraclarsController : Controller
    {
        Arac_Kiralama_ProjesiEntities db = new Arac_Kiralama_ProjesiEntities();
        // GET: Araclars
        public ActionResult arac_kaydet()
        {
            var subeler = new SelectList(db.Subeler, "sube_no", "sube_ad");
            ViewBag.sube_id = subeler;
            var  arackategori = new SelectList(db.AracKategorileri, "kategori_no", "kategori_ad");
            ViewBag.kategori_id = arackategori;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> arac_kaydet(Araclar yeni_arac,HttpPostedFileBase dosya_nesnesi)
        {
            string resim_adi = "resimyok.jpg";
            if (dosya_nesnesi != null)
            {
                string uzanti = Path.GetExtension(dosya_nesnesi.FileName);
                if (uzanti.Equals(".jpg") || uzanti.Equals(".png"))
                {
                    int son_arac_no = 0;
                    var enBuyukAracNo = db.Araclar.OrderByDescending(x => x.arac_no).FirstOrDefault();
                    if (enBuyukAracNo != null)
                    {
                        son_arac_no = enBuyukAracNo.arac_no;
                    }
                    son_arac_no += 1;
                    resim_adi = Path.GetFileName(dosya_nesnesi.FileName);
                    string tam_yol = Path.Combine(Server.MapPath("~/arac_resimleri/"), resim_adi);
                    dosya_nesnesi.SaveAs(tam_yol);
                    ViewBag.msj = "Görsel başarı ile yüklendi ve kayıt tamamlandı";
                    yeni_arac.arac_no = son_arac_no; // Arac nesnesine arac_no değerini atayın
                    yeni_arac.resim= resim_adi;
                    db.Araclar.Add(yeni_arac);
                    await db.SaveChangesAsync();
                    /* int son_arac_no = db.Araclar.Max(x => x.arac_no);
                     son_arac_no += 1;
                     resim_adi = Path.GetFileName(dosya_nesnesi.FileName);
                     string tam_yol = Server.MapPath("~/arac_resimleri/")+resim_adi;
                     dosya_nesnesi.SaveAs(tam_yol);
                     ViewBag.msj = "Görsel başarı ile yüklendi ve kayıt tamamlandı";
                     yeni_arac.resim = resim_adi;
                     db.Araclar.Add(yeni_arac);
                     await db.SaveChangesAsync();*/

                }
                else
                {
                    ViewBag.msj = "Lütfen resim dosyası seçiniz";
                }
            }
            else
            {
                ViewBag.msj = "Araç resimsiz bir şekilde kaydedildi";
                yeni_arac.resim = resim_adi;
                db.Araclar.Add(yeni_arac);
                await db.SaveChangesAsync();
            }
            var subeler = new SelectList(db.Subeler, "sube_no", "sube_ad");
            ViewBag.sube_id = subeler;
            var arackategori = new SelectList(db.AracKategorileri, "kategori_no", "kategori_ad");
            ViewBag.kategori_id = arackategori;
            return View();
        }
        public ActionResult arac_goster(int? sayfa,int?id)
        {
            var sayfa_no = sayfa ?? 1;
            var arac_listesi = db.Araclar.Where(x => x.kategori_id == id).ToList().ToPagedList(sayfa_no, 8);
            return View(arac_listesi);
        }
        public ActionResult arac_kategorileri()
        {
            var kategoriler = db.AracKategorileri.Select(x => x.kategori_ad).ToList();
            return View(kategoriler);
        }

    }
}

Arac_Kiralama_Otomasyonu/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Arac_Kiralama_Otomasyonu.Models;
using Newtonsoft.Json;

namespace Arac_Kiralama_Otomasyonu.Controllers
{

    public class HomeController : Controller
    {
        Arac_Kiralama_ProjesiEntities db = new Arac_Kiralama_ProjesiEntities();


        /* public ActionResult login_giris()
         {

             return PartialView();
         }
         [HttpPost]
         public async Task<ActionResult> login_giris(Musteriler gelen_musteri)
         {
             var musterim = await db.Musteriler.FirstOrDefaultAsync(x => x.email == gelen_musteri.email && x.sifre == gelen_musteri.sifre);
             string msj = "";
             if (musterim != null)
             {
                 Session["musterim"] = musterim;
             }
             else
             {
                 msj = "E-mail veya Şifre yanlış";
             }
             return RedirectToAction("index", new { msj });
         }*/

        public ActionResult Index(string msj)
        {
            var subelistesi = db.Subeler.ToList();
            Session["Subeler"] = subelistesi;
            // Session'da "musterim" adında bir değişken varsa ve değeri null değilse, kullanıcı giriş yapmış demektir.
            if (Session["musterim"] != null)
            {
                ViewBag.IsLoggedIn = true;
            }
            else
            {
                ViewBag.IsLoggedIn = false;
            }

            ViewBag.msj = msj;
            return View();
        }

        [HttpGet]
        public ActionResult musteri_girisi()
        {

            return View();
        }
        [HttpPost]
        public async Task<ActionResult> musteri_girisi(Musteriler gelen_musteri)
        {
            var musterim = await db.Musteriler.FirstOrDefaultAsync(x => x.email == gelen_musteri.email && x.sifre == gelen_musteri.sifre);
            string msj = "";
            if (musterim != null)
            {
                FormsAuthentication.SetAuthCookie(musterim.email, false);
                Session["musterim"] = musterim;
                return RedirectToAction("Index", "Home");
            }
            else
            {
                msj = "E-mail veya Şifre yanlış";
                ViewBag.ErrorMessage = msj;
                return View("musteri_girisi", "Home", new { msj });
            }

        }
        public ActionResult kategori_doldur()
        {

            var arac_listem = db.AracKategorileri.ToList();
            return PartialView(arac_listem);
        }
        public ActionResult guv_cikis()
        {
            Session.RemoveAll();//sessionu kaldırır
            Session.Abandon();
            return RedirectToAction("index");//ve index yani anasayfaya yönlendirir.
        }
        public ActionResult kategori_getir()
        {
            var arac_listem = db.AracKategorileri.ToList();
            return PartialView(arac_listem);

        }
        public ActionResult BizeUlasin()
        {
            return PartialView("bize_ulasin", "Home");
        }
        public ActionResult hakkımızda()
        {
            return PartialView("hakkimizda", "Home");
        }
        [HttpPost]
        public ActionResult SendMessage()
        {
            // Mesajı gönderme işlemleri...
            return Content("Talebiniz başarı ile alınmıştır, iyi günler dileriz");
        }

    }
}

Arac_Kiralama_Otomasyonu/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

Arac_Kiralama_Otomasyonu/Views/Home/bize_ulasin.cshtml
<!DOCTYPE html>
<html>

<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/template/css/responsive.css")
    @Scripts.Render("~/template/css/style.css")
    @Scripts.Render("~/template/css/style.css.map")
    @Scripts.Render("~/template/css/style.scss")
    @Scripts.Render("~/template/js/bootstrap.js")
    @Scripts.Render("~/template/js/custom.js")
    @Scripts.Render("~/template/js/jquery-3.4.1.min.js")
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>AraçKiracım.com</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="css/responsive.css" rel="stylesheet" />
</head>

<body class="sub_page">
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container">
                    <a class="navbar-brand" href="index.html">
                        <span>
                            AraçKiracım.com
                        </span>
                    </a>

                    <div class="navbar-collapse" id="">
                        <div class="user_option">
                            <a href="@Url.Action("Index", "Home")">Anasayfa</a>
                        </div>

                    </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>

    <!-- contact section -->

    <section class="contact_section layout_padding">
        <div class="container">
            <div class="heading_container">
                <h2>
                    Sizi Arayalım!
                </h2>
            </div>
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <div class="form_container">
                        <form>
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <input type="text" class="form-control" id="inputName4" placeholder="Ad ">
                                </div>
                                <div class="form-group col-md-6">
                                    <input type="text" class="form-control" id="inputSubject4" placeholder="Telefon">
                                </div>
                            </div>
                            <div class="form-row">
                                <div class="form-group col">
                                    <input type="email" class="form-control" id="inputEmail4" placeholder="Email ">
                                </div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" id="inputMessage" placeholder="Mesaj">
                            </div>
                            <form id="contactForm" action="@Url.Action("SendMessage", "Home")" method="post">
                                <!-- Form içeriği -->
                                <div class="d-flex justify-content-center">
                                    <button type="submit" id="submitBtn">Gönder</button>
                                </div>
                            </form>
                    </form>
                </div>
                </div>
            </div>
            <div class="contact_items">

                <a href="">
                    <div class="img-box">
                        <img src="~/template/images/location.png" alt="">
                    </div>
                    <h6>
                        Santral Garaj, Kıbrıs Şehitleri Cd. No:64, <br />16200 Osmangazi/Bursa
                    </h6>
                </a>
                <a href="">
                    <div class="img-box">
                        <img src="~/template/images/call.png" alt="">
                    </div>
                    <h6>
                        (+12 1234456789)
                    </h6>
                </a>
                <a href="">
                    <div class="img-box">
                        <img src="~/template/images/mail.png" alt="">
                    </div>
                    <h6>
                        arackiracım@gmail.com

                    </h6>
                </a>

            </div>
            <div class="social_container">
                <div class="social-box">
                    <div>
                        <a href="https://www.facebook.com">
                            <img src="~/template/images/fb.png" alt="">
                        </a>
                    </div>
                    <div>
                        <a href="https://twitter.com">
                            <img src="~/template/images/twitter.png" alt="">
                        </a>
                    </div>
                    <div>
                        <a href="https://www.linkedin.com">
                            <img src="~/template/images/linkedin.png" alt="">
                        </a>
                    </div>
                    <div>
                        <a href="https://www.instagram.com">
                            <img src="~/template/images/insta.png" alt="">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script>
        $(document).ready(function () {
            $('#contactForm').submit(function (e) {
                e.preventDefault(); // Formun otomatik olarak gönderilmesini engelle

                // Form verilerini AJAX isteği ile gönder
                $.ajax({
                    url: $(this).attr('SendMessage'),
                    type: $(this).attr('POST'),
                    data: $(this).serialize(),
                    success: function (response) {
                        alert(response); // Başarılı yanıtı alert ile göster
                    }
                });
            });
        });
    </script>

    <!-- end contact section -->
    <!-- footer section -->
    <footer class="container-fluid footer_section">
        <p>
            Copyright &copy; 2020 All Rights Reserved. Design by
            <a href="https://html.design/">Free Html Templates</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
        </p>
    </footer>
    <!-- footer section -->

    <script src="js/jquery-3.4.1.min.js"></script>
    <script src="js/bootstrap.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
    </script>
    <script src="js/custom.js"></script>

</body>

</html>

Arac_Kiralama_Otomasyonu/Views/Home/hakkimizda.cshtml
<!DOCTYPE html>
<html>

<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/template/css/responsive.css")
    @Scripts.Render("~/template/css/style.css")
    @Scripts.Render("~/template/css/style.css.map")
    @Scripts.Render("~/template/css/style.scss")
    @Scripts.Render("~/template/js/bootstrap.js")
    @Scripts.Render("~/template/js/custom.js")
    @Scripts.Render("~/template/js/jquery-3.4.1.min.js")
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>Rent4u</title>

    <!-- slider stylesheet -->
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />

    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="css/bootstrap.css" />

    <!-- fonts style -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,600,700&display=swap" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/style.css" rel="stylesheet" />
    <!-- responsive style -->
    <link href="css/responsive.css" rel="stylesheet" />
</head>

<body class="sub_page">
    <div class="hero_area">
        <!-- header section strats -->
        <header class="header_section">
            <div class="container-fluid">
                <nav class="navbar navbar-expand-lg custom_nav-container">
                    <a class="navbar-brand" href="index.html">
                        <span>
                            Rent4u
                        </span>
                    </a>

                    <div class="navbar-collapse" id="">
                        <div class="user_option">
                            <a href="@Url.Action("Index", "Home")">Anasayfa</a>
                        </div>
                </nav>
            </div>
        </header>
        <!-- end header section -->
    </div>

    <!-- about section -->

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Araçlarımız</title>
        <link rel="stylesheet" href="styles.css">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <h2>Araçlarımız Hakkında</h2>
                        <div class="detail-item">
                            <h3>Lüks ve Konfor</h3>
                            <p>
                                Sizi rüya gibi bir sürüş deneyimine davet ediyoruz. Konforlu koltukları ve lüks donanımıyla bu araç, yolculuklarınızı unutulmaz kılacak.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Pratik ve Ekonomik</h3>
                            <p>
                                İhtiyacınız olan her şeyi sunan bu araç, size pratiklik ve tasarrufun mükemmel bir kombinasyonunu sunuyor. Hem cebinizi, hem de zamanınızı koruyun.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Macera ve Serüven</h3>
                            <p>
                                Yollara çıkmak için can atanlar için tasarlandı! Bu araç, sizi keşfetmek için bekleyen macera dolu rotalara götürecektir. Heyecan dolu anlar yaşamak için hazır mısınız?
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Aile Dostu ve Güvenli</h3>
                            <p>
                                Ailenizle keyifli zaman geçirmek için ideal bir seçenek! Bu araç, güvenliğiyle öne çıkarken, aynı zamanda geniş iç hacmiyle ailenizin her üyesine rahatlık sunuyor.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Şehir İçi Hareketlilik</h3>
                            <p>
                                Şehirde hızlı ve pratik bir şekilde hareket etmek için ideal olan bu araç, dar sokaklarda manevra yapmayı kolaylaştırırken, çevre dostu özellikleriyle de dikkat çekiyor.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Spor ve Performans</h3>
                            <p>
                                Hız ve performans tutkunları için özel olarak tasarlandı! Bu araç, dinamik sürüş özellikleriyle adrenalin dolu anlar yaşamanızı sağlayacak.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Eko-Dostu ve Düşük Yakıt Tüketimi</h3>
                            <p>
                                Hem çevreye duyarlı, hem de cebinizi düşünen bir seçenek! Bu araç, düşük yakıt tüketimiyle sizi uzun yolculuklarda bile maliyetten tasarruf ettirecek.
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-md-4 col-lg-3">
                    <div class="detail-box">
                        <div class="detail-item">
                            <h3>Stil ve Şıklık</h3>
                            <p>
                                Tarzınızı yansıtacak bir araç mı arıyorsunuz? İşte size özel bir seçenek! Bu araç, şık tasarımı ve dikkat çekici detaylarıyla sizi farklı kılacak.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <a href="#" class="read-more-btn">Daha Fazlasını Gör</a>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f2f2f2;
                margin: 0;
                padding: 0;
            }

            .container {
                max-width: 1200px;
                margin: 0 auto;
                padding: 20px;
            }

            .detail-box {
                background-color: #f9f9f9;
                padding: 20px;
                border-radius: 10px;
                box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            }

            .detail-item {
                margin-bottom: 20px;
            }

                .detail-item h3 {
                    color: #333;
                    font-size: 18px;
                    margin-bottom: 10px;
                }

                .detail-item p {
                    color: #666;
                    font-size: 16px;
                    line-height: 1.6;
                }

            .read-more-btn {
                display: block;
                width: 100%;
                text-align: center;
                background-color: #007bff;
                color: #fff;
                padding: 10px 0;
                border-radius: 5px;
                text-decoration: none;
                transition: background-color 0.3s ease;
            }

                .read-more-btn:hover {
                    background-color: #0056b3;
                }
        </style>

        </div>
        </div>
        </div>
        </div>
    </body>
</html>



<!-- end about section -->
<!-- footer section -->
<footer class="container-fluid footer_section">
    <p>
        Copyright &copy; 2020 All Rights Reserved. Design by
        <a href="https://html.design/">Free Html Templates</a> Distributed by <a href="https://themewagon.com">ThemeWagon</a>
    </p>
</footer>
<!-- footer section -->

<script src="js/jquery-3.4.1.min.js"></script>
<script src="js/bootstrap.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
</script>
<script src="js/custom.js"></script>

</body>

</html>

Arac_Kiralama_Otomasyonu/Views/Home/kategori_doldur.cshtml
@model IEnumerable<Arac_Kiralama_Otomasyonu.Models.AracKategorileri>
@{

}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dropdown Menü</title>
    <!-- CSS Stilleri -->
    <style>
        .custom-link {
            color: #333; /* Link rengi */
            text-decoration: none; /* Altçizgi kaldır */
        }

            .custom-link:hover {
                background-color: #f8f9fa; /* Link üzerine gelindiğinde arka plan rengi */
            }

        .dropdown-menu {
            background-image: url('/template/images/hero-img.jpg/');
            background-size: cover; /* Resmi kapla */
            border: none; /* Kenarlık yok */
        }
    </style>
</head>
<body>
    <!-- Dropdown Menü -->
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="kategoriSecinizButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Kategori Seçiniz
        </button>
        <div >
            <ul class="list-unstyled">
                @foreach (var gelen_kat in Model)
                {
                    <li>
                        <a class="dropdown-item custom-link" href="@Url.Action("arac_goster", "araclars", new { id = gelen_kat.kategori_no })">
                            @gelen_kat.kategori_ad
                        </a>
                    </li>
                }
            </ul>
        </div>
    </div>

    <!-- JavaScript Bağlantısı (Bootstrap ve jQuery'nin kullanıldığı varsayılmıştır) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-j2fEPc7+O1t6a40zXmtNUt8F9j64pmssIbG3k5xK1tW5SJ9jqhQgGzDqpXhF5L7h" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

Arac_Kiralama_Otomasyonu/Views/Home/kategori_getir.cshtml
@model IEnumerable<Arac_Kiralama_Otomasyonu.Models.AracKategorileri>



 <ul class="list-unstyled">
    @foreach (var gelen_kat in Model)
    {
        <li>
           <a class="dropdown-item custom-link" href="@Url.Action("arac_goster","Araclars",new { id=gelen_kat.kategori_no})">
                @gelen_kat.kategori_ad
            </a>
        </li>
    }
</ul>

Arac_Kiralama_Otomasyonu/Views/Home/musteri_girisi.cshtml
@using Arac_Kiralama_Otomasyonu.Models;
@model Musteriler
@{
    Layout = null;
    string msj = "";
    if (Session["musterim"] != null)//sessionu burada tutup gerekli anda kullandık,üye girişi başarılı olduğu için hoşgeldiniz yazdırıdk
    {
        msj = "Hoşgeldiniz " + ((Musteriler)Session["musterim"]).ad;
    }
}
<b>@msj</b>
@if (Session["musterim"] == null)
{
    // Oturum açılmamışsa "Giriş" bağlantısını göster
    <a href="@Url.Action("musteri_girisi","Home")">    Giriş</a>
}
else
{
    // Oturum açılmışsa "Güvenli Çıkış" bağlantısını göster
    <a href="@Url.Action("guv_cikis","Home")">   Güvenli Çıkış</a>
}
@if (Session["musterim"] == null)
{
    using (Html.BeginForm("musteri_girisi", "Home")) //login giris action resultını kullandık.
    {
        <title>     Giriş Sayfası</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
        <body>
            <div class="input-container">
                <i class="fa fa-envelope icon"></i>
                @*<input type="email" placeholder="Email" name="email" class="input-field" required>*@
                @Html.TextBoxFor(model => model.email, null, new { @class = "form-control", placeholder = "         E-mail", required = true })
            </div>
            <div class="input-container">
                <i class="fa fa-key icon"></i>
                @*<input type="password" placeholder="Password" name="password" class="input-field" required>*@
                @Html.PasswordFor(model => model.sifre, new { @class = "form-control", placeholder = "       Şifre", required = true })
                <i class="fa fa-eye icon" onclick="togglePassword()"></i>
            </div>
            <div><input type="submit" class="bttn" value="GİRİŞ"></div>
        </body>
    }
    <style>
        body {
            background-image: url('/template/images/hero-img.jpg'); /* Arka plan görseli */
            background-size: cover;
            background-position: center;
            font-family: Arial, sans-serif;
        }

        .login-form {
            max-width: 300px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: rgba(255, 255, 255, 0.8); /* Arka plan rengi (saydamlık ayarlı) */
        }

        .input-container {
            position: relative;
            margin-bottom: 15px;
        }

            .input-container input {
                width: 100%;
                padding: 10px;
                border: 1px solid #ccc;
                border-radius: 3px;
            }

            .input-container .icon {
                position: absolute;
                top: 12px;
                left: 10px;
                color: #888;
            }

            .input-container .fa-eye {
                cursor: pointer;
            }

        .bttn {
            width: 100%;
            padding: 10px;
            border: none;
            border-radius: 3px;
            background-color: #007bff;
            color: #fff;
            font-size: 16px;
            cursor: pointer;
        }

            .bttn:hover {
                background-color: #0056b3;
            }
    </style>
}